/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardEntryLogsRouteImport } from './routes/_dashboard/entry-logs'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardCameraRouteImport } from './routes/_dashboard/camera'
import { Route as DashboardUsersIndexRouteImport } from './routes/_dashboard/users/index'
import { Route as DashboardUsersRegisterRouteImport } from './routes/_dashboard/users/register'
import { Route as DashboardUsersUserIdRouteImport } from './routes/_dashboard/users/$userId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEntryLogsRoute = DashboardEntryLogsRouteImport.update({
  id: '/entry-logs',
  path: '/entry-logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCameraRoute = DashboardCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRegisterRoute = DashboardUsersRegisterRouteImport.update({
  id: '/users/register',
  path: '/users/register',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersUserIdRoute = DashboardUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/camera': typeof DashboardCameraRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/entry-logs': typeof DashboardEntryLogsRoute
  '/users/$userId': typeof DashboardUsersUserIdRoute
  '/users/register': typeof DashboardUsersRegisterRoute
  '/users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/camera': typeof DashboardCameraRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/entry-logs': typeof DashboardEntryLogsRoute
  '/users/$userId': typeof DashboardUsersUserIdRoute
  '/users/register': typeof DashboardUsersRegisterRoute
  '/users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/camera': typeof DashboardCameraRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/entry-logs': typeof DashboardEntryLogsRoute
  '/_dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/_dashboard/users/register': typeof DashboardUsersRegisterRoute
  '/_dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/camera'
    | '/dashboard'
    | '/entry-logs'
    | '/users/$userId'
    | '/users/register'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/camera'
    | '/dashboard'
    | '/entry-logs'
    | '/users/$userId'
    | '/users/register'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_dashboard/camera'
    | '/_dashboard/dashboard'
    | '/_dashboard/entry-logs'
    | '/_dashboard/users/$userId'
    | '/_dashboard/users/register'
    | '/_dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/entry-logs': {
      id: '/_dashboard/entry-logs'
      path: '/entry-logs'
      fullPath: '/entry-logs'
      preLoaderRoute: typeof DashboardEntryLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/camera': {
      id: '/_dashboard/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof DashboardCameraRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users/': {
      id: '/_dashboard/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users/register': {
      id: '/_dashboard/users/register'
      path: '/users/register'
      fullPath: '/users/register'
      preLoaderRoute: typeof DashboardUsersRegisterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users/$userId': {
      id: '/_dashboard/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof DashboardUsersUserIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCameraRoute: typeof DashboardCameraRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardEntryLogsRoute: typeof DashboardEntryLogsRoute
  DashboardUsersUserIdRoute: typeof DashboardUsersUserIdRoute
  DashboardUsersRegisterRoute: typeof DashboardUsersRegisterRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCameraRoute: DashboardCameraRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardEntryLogsRoute: DashboardEntryLogsRoute,
  DashboardUsersUserIdRoute: DashboardUsersUserIdRoute,
  DashboardUsersRegisterRoute: DashboardUsersRegisterRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
